client/views/statutory/ViewApplication.vue

As Chair team mentioned:
We received some complaints from applicants for the EPM and boards that the board comments in OMS seem to be visible to the applicants. Could you check this and if yes, disable this functionality, as this could limit boards in making honest comments in the future.
Thank you already! We wish you a merry Christmas and a happy new year!
To be merged ASAP.

Hide board comment when displaying application

---

docker/Dockerfile
docker/bootstrap-dev.sh
docker/docker-compose.dev.yml

The mounts do not speed up anything, rather slow people down.
As the container has to be rebuilt anyway, this way it just works

fix(docker): remove useless mount

---

src/components/layout/FooterBar.vue
src/views/static/ConfluencePage.vue

Also kinda related: can we make `/legal/simple` be a confluence page instead of a static page?

chore: add ToS among static pages

---

package.json
vue.config.js

As homework:
* enable in nginx `gzip_static on;` so that the .gz files are delivered to the users.
* ensure that Node JS is at least 11.7 or install optional dependency iltorb
* ensure that nginx has the [ngx_brotli](https://github.com/google/ngx_brotli) module .
* enable in nginx `brotli_static on;` so that the .br files are delivered to the users.

feat: compress the output using gz/zopfli and brotli

---

.browserslistrc

Per https://www.ssllabs.com/ssltest/analyze.html?d=my.aegee.eu Internet Explorer Desktop 10, IE Mobile 10 and IE Mobile 11 cannot connect to https://my.aegee.eu.

fix(.browserslist): don't generate code for IE mobile 10

---

src/styles/main.scss

somehow animate.css was used and wasn't imported, so styles weren't applied, that's why sidebar was stuck.

fix(sidebar): fix sidebar being stuck for mobile

---

src/components/layout/Sidebar.vue

apparently upgrading animate.css to 4.x was a breaking change and all of the classes have `animate__` prefix before them: https://animate.style/#migration

fix(sidebar): fix sidebar being stuck for mobile, again

---

src/views/statutory/QuestionLinesList.vue

Formerly the ID of the question line was the internal ID, which did not reset with every Agora. Now the ID will just be the index + 1.

fix(question line): Updated ID of question line

---

src/services.json

`s/api\/core/services\/oms-core-elixir\/api` for backwards compatibility

chore(services): revert oms-core-elixir prefix

---

src/views/core/bodies/ViewJoinRequests.vue
src/views/static/Status.vue

1) in the new schema, field is `inserted_at`, not `created_at`, also I've updated all join requests to have normal dates
2) added some workarounds for /status page, so it'd work with service accessible at `/services/oms-core-js/api` but named `oms-core-js`

fix(general): fix join request date

---

src/fontawesome.js
src/views/core/bodies/Single.vue

there's no DELETE /bodies/:id endpoint anymore, there's PUT /bodies/:id/status now, as bodies are not physically deleted. this reflects changes on the backend, I somehow forgot to add it there.
also adding fa-exclamation-circle icon to display the icon on notification popup

fix(bodies): allow setting bodies as deleted

---

src/views/core/permissions/Edit.vue
src/views/core/permissions/Single.vue

in old core, permission filters were an array of objects with `id` and `field` fields, in the new core it's just an array of strings

fix(permissions): fixed permissions filters editing and displaying

---

.circleci/config.yml
src/router/routes.js
src/views/auth/MailChange.vue
src/views/core/members/Single.vue

added new email change prompt and a page to confirm it (basically a copypaste of a token confirmation after logging in, but  auth-only).
How it works:
1) user asks for an email change
2) a letter is sent to a new inbox, with the token
3) user opens it, inputs a token, presses 'confirm',  voila, the email is confirmed and changed for a user.
If the token is not used for 2 days, it's deleted from the system, so no way to change the email to not-existing one.
https://github.com/AEGEE/core/pull/42 should be merged and deployed before though.

feat(members): allow email change

---

src/views/core/bodies/AddMemberModal.vue
src/views/core/bodies/Single.vue

added a modal to add members to a body, added a button that is displayed if you have permissions to do so. It's only accessible if you can see members globally (`global:view:member`), so admins only.

feat(members): add member to a body. Fixes MEMB-794

---

src/views/core/members/List.vue

the b-table's pagination starts with 1 and not 0, need to respect this.

fix(members): fixed members pagination when switching page

---

.browserslistrc

by deleting `.browserslistrc` and relaying on the defaults.

Add support for Firefox 68 (Extended Support Release)

---

src/views/core/bodies/Single.vue
src/views/statutory/PositionsList.vue

Should fix that nothing shows up when the task description is not set at an Agora position.
Also deletes the category from the body overview, if it was set in the past but now empty again

fix: different weird things with empty task descriptions

---

src/views/core/bodies/Single.vue
src/views/statutory/PositionsList.vue

should in theory fix https://myaegee.atlassian.net/browse/HELP-1272
selectedPosition doesn't have `task_description` field, as it's in the body, so it won't work I assume. works locally, not sure if it'll work on production, but should in theory.

fix(bodies): fix task descriptions. Fixes HELP-1272

---

src/views/static/Status.vue

added the displaying of latest Docker tag, just in case there's a mismatch between the one in master and the one on Dockerhub (for example, when the version is bumped already, but the docker tag is not pushed yet)

feat(status): fetch docker tag

---

src/views/core/bodies/Single.vue

Only admins and CD should be able to view so I created a check for a new permission. Will add the permission to MyAEGEE myself
Did not add the permission to the permissions seeder in core, but will do that in a different PR later

fix(bodies): Only show shadow circles if permitted

---

docker/docker-compose.dev.yml

As discussed on Slack, the docker compose file should by default allow building on host

chore: update docker compose to allow building on host

---

src/auth.js

failing all requests if no access/refresh tokens was too much (as there are requests that could be done unauthorized), so at least fetching the user is now not performed if no tokens are provided. This should reduce the number of requests to core when somebody is accessing my.aegee.eu while being unauthorized (before we tried to load the user information, now we are not even trying to if no tokens are provided)

fix(general): fail request if no access token

---

src/views/statutory/ListMembersLists.vue

apparently we send `fee_paid` as string and for whatever reason backend also returns it as string (it stores it properly though), so I've done 2 things: converting this value to a float and 2) updated the input so it'd only accept float values (so if you'll type `aaa`, it'll complain)

fix(statutory): fix setting fee paid for members list. Fixes HELP-1305

---

src/views/events/Apply.vue
src/views/events/Edit.vue

EQAC wanted two extra disclaimers on the event page.
This PR adds a COVID warning for both participants and organizers, and an info for organizers to plan for water access.

feat(ma-33): add disclaimer and other info to event creation

---

src/views/core/members/Single.vue

this is hard-deleting, soft-deleting would be done later. We also need global:delete:member permission for that, so a person by himself/herself cannot delete the profile. This is for admins/helpdesk agents only.

feat(users): allow deleting users. Fixes MA-100

---

src/components/layout/Sidebar.vue
src/menu.json
src/router/routes.js
src/views/core/members/ListUnconfirmed.vue

frontend for https://github.com/AEGEE/core/pull/152

feat(general): allow listing and confirming users manually. Fixes MA-77

---

src/views/events/Edit.vue

Since adding online events is not fully implemented in MyAEGEE, I've added some help for event organizers which do not have a budget since online events are free.

fix(events): Add help for placeholder budget link. Fixes HELP-1360

---

src/views/statutory/EditApplication.vue

It was only changed with new applications in the [previous PR](https://github.com/AEGEE/frontend/pull/682), so now a quick fix for this when users edit their current application.

fix(statutory): edit application now only shows applicable bodies

---

src/views/dashboard/index.vue

The events on the dashboard should now only be displayed if you have not cancelled them, and got accepted to that event. Needs to be merged together with two other PR's for the backend.
Fixes [HELP-1477](https://myaegee.atlassian.net/servicedesk/customer/portal/1/HELP-1477)

fix(events): only display events you are going to. Fixes HELP-1477

---

src/views/events/Edit.vue
src/views/events/Single.vue
src/views/statutory/Edit.vue
src/views/statutory/Single.vue
src/views/summeruniversity/Edit.vue
src/views/summeruniversity/EditSecond.vue
src/views/summeruniversity/Single.vue

fitBounds only looked at the first two locations. This makes it work for more than 2 locations

fix(map): define bounds for more than 2 locations

---

src/views/dashboard/Calendar.vue

It's all 1 query and shouldn't be that much data so it's fine to remove it instead of requerying it everytime you move months (and that is currently broken anyway)

fix(calendar): fetch all events. Fixes HELP-1616

---

src/views/auth/Register.vue
src/views/core/bodies/CampaignsList.vue
src/views/core/campaigns/Edit.vue
src/views/core/campaigns/List.vue
src/views/core/campaigns/Single.vue

Frontend for https://github.com/AEGEE/core/pull/266

feat(campaign): add name and description

---

package-lock.json
package.json

I also fixed some audit stuff regarding npm so the changes are a bit more than expected. 
According to https://github.com/apertureless/vue-chartjs/issues/695 chart.js v3 support is not yet added to vue-chartjs

chore(deps): revert chart.js to 2.9.4

---

src/views/core/bodies/Edit.vue

Address is not required anymore in core, I forgot to remove this in the previous PR.
Abbreviation must be unique in core, and so the validation failed. Now there is no data being put in the database anymore
Fixes part of HELP-1666

fix(body): fix abbreviation. Fixes HELP-1666

---

src/views/dashboard/Calendar.vue

During the hackathon we forgot that the description can contain markdown, but we did not add rendering for that.

fix(calendar): add markdown to event description

---

src/menu.json

Not sure why it works for global permissions, but not with local permissions. But it's the way it is, this is an okay fix for now.

chore(menu): remove permission

---

src/views/events/Edit.vue
src/views/events/Single.vue
src/views/statutory/Edit.vue
src/views/statutory/Single.vue
src/views/summeruniversity/Edit.vue
src/views/summeruniversity/EditSecond.vue
src/views/summeruniversity/Single.vue

By changing the zoom to 3 we do not load something very zoomed in which will take a lot of tiles if we fly across Europe. This should theoretically lower the amount of tile requests to MapTiler.

fix(map): increase zoom

---

src/views/statutory/EditCandidate.vue

As mentioned by Vale privately.
Using `created_at` for `member_since` is not the nicest solution but people can still update it.

fix(statutory): prefill email and date of birth for candidates

---

src/nationalities.json

As per request of a member, forwarded by SUCT

fix: add Hong Kongese to nationalities list

---

src/views/events/BoardView.vue
src/views/summeruniversity/BoardView.vue

Change the board view of the events (both for "regular" events and SU's) to:
- Sort based on the "updated_at" column automatically, so board members can find new applications easier
- Have a textarea field instead of an input field for the board comment (makes it the same as for statutory)

Update board view events

---

src/views/core/members/Single.vue

It is unclear which email is set as notification email in the frontend, this change improves this. Finding the non-GSuite email of the user is still possible for admins by going to the edit page of a profile (or by using the API).

fix(core): display notification email instead of email in user profile
