AEGEE/frontend

- client/views/statutory/MassMailer.vue
- client/views/statutory/Single.vue
WIP, to merge once it will work on staging.
> Improved massmailer

- client/styles/main.scss
- client/views/core/bodies/AddBoundCircleModal.vue
- client/views/core/bodies/Single.vue
- client/views/core/circles/AddMemberModal.vue
- client/views/core/circles/EditMemberPositionModal.vue
- client/views/core/circles/Single.vue
- client/views/core/circles/ViewMembers.vue
- package-lock.json
- package.json
Fixes https://oms-project.atlassian.net/browse/MEMB-228
Also updated Buefy.
> Fix modals. Fixes MEMB-228

- client/components/layout/Sidebar.vue
- package-lock.json
- package.json
> Removed vue-bulma-expanding. Fixes MEMB-264

- client/views/core/bodies/List.vue
self-explanatory. Will merge when it will work on the frontend.
> Filter on body type and display body types on listing. Fixes MEMB-214

- client/menu.json
> Remove events from menu for now, will restore after oms-events refactor

- client/views/statutory/Single.vue
just realized that the displaying single statutory event doesn't work.
> Fixed displaying statutory single event

- client/views/statutory/EditPositionModal.vue
- client/views/statutory/PositionsList.vue
so it'd automatically fetch the updated/created position.
> Reloading page on position creation/edition

- client/views/statutory/BoardView.vue
- client/views/statutory/Edit.vue
- client/views/statutory/Incoming.vue
Will fix MEMB-385, MEMB-381 and MEMB-398
> Improvements from Chair feedback

- client/views/static/Discounts.vue
10% discount instead of 3 euro
> Fixed Flixbus discount description

- client/views/static/Discounts.vue
Now it's mobile friendly, also fixed icons that were crashed during FA5 migration.
> Fixed discounts view

- client/views/dashboard/index.vue
- client/views/statutory/Edit.vue
- client/views/statutory/Single.vue
Fixes MEMB-392. Related: https://github.com/AEGEE/oms-statutory/pull/11
> Pax list display

- client/components/layout/FooterBar.vue
- client/router/routes.js
- client/styles/main.scss
- client/views/static/BugReport.vue
- package-lock.json
- package.json
> Bug report form

- client/menu.json
- client/views/events/Apply.vue
- client/views/events/BoardView.vue
- client/views/events/ChangeStatus.vue
- client/views/events/Edit.vue
- client/views/events/EditOrganizers.vue
- client/views/events/List.vue
- client/views/events/Participants.vue
- client/views/events/ServiceAdmin.vue
- client/views/events/Single.vue
frontend changes for https://github.com/AEGEE/oms-events/pull/39, WIP
> oms-events refactor

- client/views/events/Accepted.vue
- client/views/events/Edit.vue
- client/views/statutory/Edit.vue
- client/views/statutory/ListMembersLists.vue
- client/views/statutory/PaxLimits.vue
> Remove $forceUpdate

- client/views/events/Single.vue
Forgot to put it there in the first place lol
> Fixed events deletion

- client/views/events/Single.vue
- client/views/statutory/Stats.vue
I messed up last update, now it should be okay.
> Proper deleting events

- client/router/routes.js
- client/views/statutory/Incoming.vue
- client/views/statutory/Juridical.vue
- client/views/statutory/Single.vue
Fixes MEMB-390, also related: https://github.com/AEGEE/oms-statutory/pull/12
> Removed departed from incoming view

- client/app.js
- client/components/SelectOrCustom.vue
- client/views/core/members/Edit.vue
- client/views/core/members/EditUser.vue
- client/views/statutory/EditApplication.vue
Fixes MEMB-399 and MEMB-396. Also fixes username regex (HELP-230), I've messed it up before.
> Gender error display

- client/views/statutory/Accepted.vue
> b-table for pax list for statutory

- client/views/core/members/Single.vue
> Fix going from one user profile page to another

- docker/oms-frontend-nginx/Dockerfile.dev
Should fix https://github.com/AEGEE/oms-docker/pull/73
> Fixed Dockerfile when dist folder is not present

- client/views/auth/Login.vue
> Add auth0 badge

- client/views/statutory/Accepted.vue
> Display accepted participants amount on participants list

- client/views/core/circles/Single.vue
> Added word-break for circle permission list

- client/app.js
- client/components/PasswordToggle.vue
- client/views/auth/Login.vue
- client/views/auth/PasswordConfirm.vue
- client/views/core/members/EditUser.vue
> Add password toggle

- client/views/statutory/EditApplication.vue
> Removed asterisk on Visa required field on statutory

- client/views/statutory/UploadMembersList.vue
> Refactored memberslist upload, allow zero values and add CSV upload.

- client/views/statutory/Export.vue
- package.json
> Select fields for statutory export

- client/views/statutory/Stats.vue
- package-lock.json
- package.json
> Refactor and improve statutory statistics

- client/views/statutory/Applications.vue
- package-lock.json
- package.json
> Display if user is on memberslist

- client/views/core/bodies/Single.vue
> fix(bodies): fixed single bodies page

- client/views/core/members/Single.vue
> Respect local permissions to suspend users

- .npmrc
- CHANGELOG.md
- commitlint.config.js
- package-lock.json
- package.json
> Add conventional commits

- CHANGELOG.md
- client/views/core/bodies/AddFeePaymentModal.vue
- client/views/core/bodies/ListFeePaymentsModal.vue
- client/views/core/bodies/ViewMembers.vue
- package-lock.json
- package.json
Fixes MEMB-462. Related: MEMB-397
> Fix fee management

- CHANGELOG.md
- client/views/events/Edit.vue
- client/views/statutory/Edit.vue
- client/views/statutory/EditCandidate.vue
- package-lock.json
- package.json
> Fix input tag trimming

- CHANGELOG.md
- client/views/static/LegalSimple.vue
- package-lock.json
- package.json
> Fix gdpr page

- CHANGELOG.md
- client/components/layout/FooterBar.vue
- package-lock.json
- package.json
> Fix footer year

- CHANGELOG.md
- client/views/events/Apply.vue
- package-lock.json
- package.json
> Display error application errors

- CHANGELOG.md
- client/views/events/Apply.vue
- client/views/events/Participants.vue
- package-lock.json
- package.json
> Add applications export

- CHANGELOG.md
- client/views/core/campaigns/Single.vue
- client/views/core/members/Single.vue
- package-lock.json
- package.json
Fixes HELP-320, related: MEMB-397
> Refactor single campaign page

- CHANGELOG.md
- client/app.js
- package-lock.json
- package.json
> Fix page title change

- CHANGELOG.md
- client/views/core/bodies/BulkImport.vue
- client/views/core/bodies/CampaignsList.vue
- client/views/core/bodies/List.vue
- client/views/core/bodies/ViewJoinRequests.vue
- client/views/core/campaigns/List.vue
- client/views/core/circles/List.vue
- client/views/core/circles/ViewMembers.vue
- client/views/core/members/List.vue
- client/views/core/permissions/List.vue
- client/views/events/BoardView.vue
- client/views/events/ChangeStatus.vue
- client/views/events/Participants.vue
- client/views/events/ViewParticipantModal.vue
- client/views/statutory/Applications.vue
- client/views/statutory/DisplayMembersListModal.vue
- client/views/statutory/Incoming.vue
- client/views/statutory/Juridical.vue
- client/views/statutory/ListMembersLists.vue
- package-lock.json
- package.json
Fixes MEMB-397, MEMB-468, MEMB-476.
> b-table everywhere

- client/views/core/members/List.vue
- client/views/events/ViewParticipantModal.vue
Fixing what I've broke in the previous PR :D
> Fix members listing

- CHANGELOG.md
- client/views/statutory/BoardView.vue
- package-lock.json
- package.json
> Display statutory boardview validation

- CHANGELOG.md
- client/views/events/Single.vue
- package-lock.json
- package.json
> Fix events map zoom

- CHANGELOG.md
- client/router/routes.js
- client/views/statutory/NetworkListing.vue
- client/views/statutory/Single.vue
- package-lock.json
- package.json
> Manage members list status

- CHANGELOG.md
- client/views/core/bodies/Single.vue
- package-lock.json
- package.json
> Pending join request mark

- CHANGELOG.md
- client/views/core/bodies/BulkImport.vue
- client/views/statutory/UploadMembersList.vue
- package-lock.json
- package.json
> Improve csv upload

- CHANGELOG.md
- client/views/events/List.vue
- package-lock.json
- package.json
> Fix events listings

- CHANGELOG.md
- client/views/statutory/ListMembersLists.vue
- package-lock.json
- package.json
> Do not load bodies on memberslist view

- CHANGELOG.md
- client/views/events/ChangeStatus.vue
- client/views/events/Edit.vue
- package-lock.json
- package.json
> Fix event question deletion

- CHANGELOG.md
- client/views/events/EditOrganizers.vue
- package-lock.json
- package.json
> Fix event organizer management

- CHANGELOG.md
- client/filters/index.js
- client/router/routes.js
- client/views/statutory/EditPlenaryModal.vue
- client/views/statutory/PlenariesList.vue
- client/views/statutory/Single.vue
- client/views/statutory/ViewPlenary.vue
- package-lock.json
- package.json
> Add plenary attendance

- CHANGELOG.md
- client/styles/main.scss
- client/views/statutory/Applications.vue
- client/views/statutory/BoardView.vue
- client/views/statutory/Single.vue
- client/views/statutory/UploadMembersList.vue
- client/views/statutory/ViewApplication.vue
- package-lock.json
- package.json
> Add memberslist fee info

- CHANGELOG.md
- client/views/statutory/Accepted.vue
- client/views/statutory/ViewApplication.vue
- package-lock.json
- package.json
> Display acceptance info to pax

- CHANGELOG.md
- client/views/statutory/EditCandidate.vue
- client/views/statutory/PositionsList.vue
- package-lock.json
- package.json
> Refactor candidates

- CHANGELOG.md
- client/views/auth/ConfirmToken.vue
- package-lock.json
- package.json
> Disable automatic confirm

- CHANGELOG.md
- client/views/core/bodies/ViewJoinRequests.vue
- package-lock.json
- package.json
> Display links to join requests profiles

- CHANGELOG.md
- client/views/statutory/PositionsList.vue
- client/views/statutory/ViewCandidateModal.vue
- package-lock.json
- package.json
> Changing position status

- CHANGELOG.md
- client/views/auth/ConfirmToken.vue
- package-lock.json
- package.json
> Fix mail confirmation

- CHANGELOG.md
- build/webpack.prod.conf.js
- client/app.js
- client/menu.json
- client/router/routes.js
- client/views/static/About.vue
- package-lock.json
- package.json
> Rename oms to myaegee

- CHANGELOG.md
- client/views/statutory/EditApplication.vue
- client/views/statutory/ViewApplication.vue
- package-lock.json
- package.json
> Fix number of SPMs visited

- CHANGELOG.md
- client/router/routes.js
- client/services.json
- client/views/discounts/AddCodes.vue
- client/views/discounts/Edit.vue
- client/views/discounts/List.vue
- client/views/discounts/MyDiscounts.vue
- client/views/static/Discounts.vue
- package-lock.json
- package.json
> Add discounts

- CHANGELOG.md
- client/views/statutory/Stats.vue
- package-lock.json
- package.json
> More colors to statutory stats

- CHANGELOG.md
- client/views/statutory/Applications.vue
- client/views/statutory/BoardView.vue
- client/views/statutory/ViewApplication.vue
- package-lock.json
- package.json
> Add waiting list pax type for statutory

- CHANGELOG.md
- client/components/layout/Sidebar.vue
- package-lock.json
- package.json
> Refactor sidebar

- CHANGELOG.md
- client/methods/index.js
- client/views/statutory/BoardView.vue
- package-lock.json
- package.json
> Refactor statutory boardview

- CHANGELOG.md
- client/views/core/bodies/Edit.vue
- client/views/core/bodies/List.vue
- client/views/core/bodies/Single.vue
- package-lock.json
- package.json
> Add founded ad for bodies

- CHANGELOG.md
- client/views/statutory/Accepted.vue
- client/views/statutory/Applications.vue
- client/views/statutory/BoardView.vue
- client/views/statutory/Export.vue
- client/views/statutory/Incoming.vue
- client/views/statutory/Juridical.vue
- client/views/statutory/NetworkListing.vue
- client/views/statutory/ViewApplication.vue
- client/views/statutory/VotesAmounts.vue
- package-lock.json
- package.json
> Add statutory ID

- CHANGELOG.md
- client/views/static/Resources.vue
- package-lock.json
- package.json
> Refactor resources page

- CHANGELOG.md
- client/views/statutory/Edit.vue
- client/views/statutory/EditCandidate.vue
- client/views/statutory/List.vue
- client/views/statutory/PositionsList.vue
- client/views/statutory/Single.vue
- client/views/statutory/ViewCandidateModal.vue
- package-lock.json
- package.json
> Statutory images upload

- CHANGELOG.md
- client/filters/index.js
- client/views/events/Apply.vue
- client/views/statutory/EditApplication.vue
- commitlint.config.js
- package-lock.json
- package.json
> Switch to select for body selecting

- CHANGELOG.md
- client/views/statutory/UploadMembersList.vue
- package-lock.json
- package.json
> Disable CSV memberslist upload

- CHANGELOG.md
- client/views/statutory/EditApplication.vue
- client/views/statutory/UploadMembersList.vue
- package-lock.json
- package.json
> Fix memberslist permissions

- CHANGELOG.md
- client/views/statutory/Edit.vue
- client/views/statutory/Single.vue
- package-lock.json
- package.json
> Add memberslist submission deadline

- CHANGELOG.md
- client/views/statutory/Stats.vue
- package-lock.json
- package.json
> Fix statutory stats ticks

- CHANGELOG.md
- client/router/routes.js
- client/services.json
- client/views/static/Status.vue
- docker/oms-frontend-nginx/sites/default.conf
- package-lock.json
- package.json
> Add backends status

- CHANGELOG.md
- client/views/core/members/Single.vue
- package-lock.json
- package.json
> Fix activate user icon

- CHANGELOG.md
- client/views/statutory/UploadMembersList.vue
- package-lock.json
- package.json
> Fix memberslists permissions issue

- CHANGELOG.md
- client/views/events/Apply.vue
- package-lock.json
- package.json
> Add events application consent

- CHANGELOG.md
- client/views/events/Apply.vue
- package-lock.json
- package.json
> Fix events application consent text

- CHANGELOG.md
- client/views/statutory/BoardView.vue
- client/views/statutory/Single.vue
- package-lock.json
- package.json
> Fix statutory boardview displaying

- CHANGELOG.md
- client/router/routes.js
- client/views/statutory/EditQuestionLineModal.vue
- client/views/statutory/EditQuestionModal.vue
- client/views/statutory/QuestionLinesList.vue
- client/views/statutory/Single.vue
- package-lock.json
- package.json
> Add statutory question lines

- CHANGELOG.md
- build/vue-loader.conf.js
- client/views/statutory/MassMailer.vue
- client/views/statutory/QuestionLinesList.vue
- package-lock.json
- package.json
Fixes MEMB-597, MEMB-590, MEMB-593
> Fix minor tweaks

- CHANGELOG.md
- client/filters/index.js
- client/styles/main.scss
- package-lock.json
- package.json
> Fix markdown lines breaking

- CHANGELOG.md
- client/router/routes.js
- client/views/statutory/Debug.vue
- package-lock.json
- package.json
> Add statutory debug page

- CHANGELOG.md
- client/router/routes.js
- client/views/statutory/TasksList.vue
- package-lock.json
- package.json
> Add statutory tasks list page

- CHANGELOG.md
- client/views/statutory/EditCandidate.vue
- client/views/statutory/TasksList.vue
- package-lock.json
- package.json
> Few minor fixes

- CHANGELOG.md
- client/views/statutory/Applications.vue
- client/views/statutory/Incoming.vue
- client/views/statutory/Juridical.vue
- client/views/statutory/NetworkListing.vue
- package-lock.json
- package.json
> Add statutory pagination

- CHANGELOG.md
- client/views/statutory/QuestionLinesList.vue
- package-lock.json
- package.json
> Allow deleting question lines

- CHANGELOG.md
- client/router/routes.js
- client/views/core/circles/List.vue
- client/views/static/ConfluencePage.vue
- package-lock.json
- package.json
Fixes MEMB-540, blocked by https://github.com/AEGEE/oms-docker/pull/86
> Visualizing Confluence pages.

- CHANGELOG.md
- client/views/statutory/EditPositionModal.vue
- client/views/statutory/PositionsList.vue
- package-lock.json
- package.json
> Add force close deadline to candidates

- CHANGELOG.md
- client/constants.js
- client/menu.json
- client/router/routes.js
- client/views/events/ChangeStatus.vue
- client/views/events/Edit.vue
- client/views/events/List.vue
- client/views/events/Single.vue
- package-lock.json
- package.json
> Events fixes

- CHANGELOG.md
- client/components/PasswordToggle.vue
- package-lock.json
- package.json
> Fix login password placeholder

- CHANGELOG.md
- client/views/events/Edit.vue
- client/views/static/About.vue
- package-lock.json
- package.json
> Add hyperlinks to about page

- CHANGELOG.md
- client/App.vue
- client/app.js
- client/components/layout/AppMain.vue
- client/components/layout/Sidebar.vue
- client/menu.json
- client/router/routes.js
- client/store/modules/app.js
- client/store/modules/menu.js
- client/views/statutory/PositionsList.vue
- package-lock.json
- package.json
Fixes MEMB-615, MEMB-467, HELP-627
> Change positions text

- CHANGELOG.md
- client/views/auth/Login.vue
- client/views/core/members/Edit.vue
- package-lock.json
- package.json
> Switch to select on member edit

- CHANGELOG.md
- client/app.js
- client/views/auth/Login.vue
- package-lock.json
- package.json
> Forward previous URL after login

- CHANGELOG.md
- client/app.js
- client/auth.js
- package-lock.json
- package.json
> Fix unauthorized redirect

- CHANGELOG.md
- client/views/statutory/PositionsList.vue
- package-lock.json
- package.json
> Allow editing candidates for admins/JC

- docker/Dockerfile
- docker/bootstrap-dev.sh
- docker/docker-compose.dev.yml
- docker/docker-compose.yml
> impr(docker): manifest is now perfect

- CHANGELOG.md
- client/views/statutory/QuestionLinesList.vue
- package-lock.json
- package.json
> Add questions indexes

- CHANGELOG.md
- client/router/routes.js
- client/views/events/Apply.vue
- client/views/events/List.vue
- client/views/events/Single.vue
- package-lock.json
- package.json
feat(event): events refactor. Fixes MEMB-620
> Events applications refactor

- CHANGELOG.md
- client/router/routes.js
- client/views/events/Apply.vue
- client/views/events/List.vue
- client/views/events/Single.vue
- package-lock.json
- package.json
> Allow seeing events application

- CHANGELOG.md
- client/menu.json
- client/router/routes.js
- package-lock.json
- package.json
> Allow unauthorized events listing

- CHANGELOG.md
- client/menu.json
- client/router/routes.js
- client/styles/main.scss
- client/views/dashboard/Calendar.vue
- package-lock.json
- package.json
Fixes MEMB-313 and a bunch of other tickets
> Add calendar

- CHANGELOG.md
- client/views/dashboard/Calendar.vue
- package-lock.json
- package.json
> First day as Monday for calendar

- CHANGELOG.md
- client/router/routes.js
- package-lock.json
- package.json
Fixes MEMB-680, HELP-720, HELP-719 and probably a few others
> Allow unauthorized access for stuff

- CHANGELOG.md
- client/app.js
- client/menu.json
- client/router/routes.js
- client/views/core/bodies/List.vue
- client/views/core/bodies/Single.vue
- package-lock.json
- package.json
> Allow unauthorized bodies access

- CHANGELOG.md
- client/app.js
- client/credentials.js
- client/styles/main.scss
- client/views/events/Apply.vue
- client/views/events/Edit.vue
- client/views/events/Single.vue
- package-lock.json
- package.json
Fixes MEMB-640, MEMB-704, MEMB-466, HELP-721, HELP-667, HELP-443, and probably some other issues (wow, that's a lot).
> Use mapbox for maps

- CHANGELOG.md
- client/views/events/Edit.vue
- client/views/static/Status.vue
- package-lock.json
- package.json
> Add events organizers disclaimer

- CHANGELOG.md
- client/views/events/List.vue
- package-lock.json
- package.json
> Display images on events listings

- CHANGELOG.md
- client/constants.js
- client/views/dashboard/Calendar.vue
- client/views/events/List.vue
- package-lock.json
- package.json
> Calendar fixes

- CHANGELOG.md
- client/views/core/bodies/List.vue
- package-lock.json
- package.json
> Fix body permissions loading

- CHANGELOG.md
- client/views/statutory/ListMembersLists.vue
- package-lock.json
- package.json
> Fixed memberslists lists sorting

- CHANGELOG.md
- client/App.vue
- package-lock.json
- package.json
> Remove touch events on desktop

- CHANGELOG.md
- client/views/events/Edit.vue
- client/views/events/EditOrganizers.vue
- package-lock.json
- package.json
> Update event bodies settings

- CHANGELOG.md
- client/views/core/bodies/ViewMembers.vue
- package-lock.json
- package.json
> Add payments sorting for members

- CHANGELOG.md
- client/components/notifications/EventNoBodyNotification.vue
- client/components/notifications/TimezoneNotification.vue
- client/views/events/Apply.vue
- client/views/events/Edit.vue
- client/views/statutory/Edit.vue
- client/views/statutory/EditApplication.vue
- package-lock.json
- package.json
> Move notifications to components

- CHANGELOG.md
- client/views/statutory/Accepted.vue
- client/views/statutory/Applications.vue
- client/views/statutory/Export.vue
- client/views/statutory/Incoming.vue
- client/views/statutory/Juridical.vue
- client/views/statutory/MassMailer.vue
- client/views/statutory/Stats.vue
- client/views/statutory/ViewApplication.vue
- package-lock.json
- package.json
> Rename paid_fee to confirmed

- CHANGELOG.md
- client/views/statutory/Edit.vue
- client/views/statutory/Single.vue
- package-lock.json
- package.json
> Add statutory locations

- CHANGELOG.md
- client/views/statutory/Export.vue
- package-lock.json
- package.json
> Expose constants as endpoints

- CHANGELOG.md
- client/views/events/Participants.vue
- client/views/events/ViewParticipantModal.vue
- package-lock.json
- package.json
> Add attended and confirmed fields

- CHANGELOG.md
- client/views/core/bodies/ViewMembers.vue
- client/views/core/circles/ViewMembers.vue
- client/views/statutory/Applications.vue
- client/views/statutory/BoardView.vue
- package-lock.json
- package.json
Fixes MEMB-825, HELP-699 and a few others.
> Hide memberslist fields for not agora

- CHANGELOG.md
- client/router/routes.js
- client/views/statutory/EditCandidate.vue
- client/views/statutory/ExportCandidates.vue
- client/views/statutory/PositionsList.vue
- package-lock.json
- package.json
> Add candidates export

- .circleci/config.yml
- CHANGELOG.md
- client/views/events/List.vue
- client/views/events/Single.vue
- package-lock.json
- package.json
> Cache events bodies names

- CHANGELOG.md
- client/views/events/ChangeStatus.vue
- client/views/events/Edit.vue
- client/views/events/Single.vue
- package-lock.json
- package.json
> Add additional fields for EQAC

- CHANGELOG.md
- package-lock.json
- package.json
- src/views/statutory/Stats.vue
> Add cancelled to statutory stats

- CHANGELOG.md
- package-lock.json
- package.json
- src/views/static/Resources.vue
> Add strategic plan to resources

- CHANGELOG.md
- package-lock.json
- package.json
- src/views/dashboard/index.vue
- list of bodies of a user are ordered alphabetically
- if primary body is set, it appears first and bold
Jira ticket: https://myaegee.atlassian.net/browse/MEMB-796
> MEMB-796: Order user bodies list

- CHANGELOG.md
- package-lock.json
- package.json
- src/views/dashboard/index.vue
> fix: show primary body when is the only one existing

- src/views/dashboard/index.vue
> feat: list circles alphabetically in dashboard

- .eslintrc.js
- src/views/statutory/Stats.vue
MEMB-798
MEMB-799
Needs also changes in backend, see statutory
> feat: add meal preference chart, remove title

- src/styles/main.scss
- src/views/dashboard/index.vue
All bodies are sorted in alphabetical order, and the primary body is in bold. Also adds a little easter egg for ITC members :p
> feat: add style bodies dashboard

- CHANGELOG.md
- package-lock.json
- package.json
- src/views/dashboard/index.vue
Fixes HELP-959 and probably a few others
> Fix dashboard with no primary body

- src/styles/main.scss
- src/views/dashboard/index.vue
-Split the events on the dashboard by upcoming and past events
-Add statutory events to the list of events you have applied for
-Sort all events on dashboard based on date
Corresponds with [MEMB-825](https://myaegee.atlassian.net/browse/MEMB-825)
> Dashboard split events

- .circleci/config.yml
- .releaserc
- package-lock.json
- package.json
> Added semantic-release

- src/views/statutory/Stats.vue
> Fix quorum data

- src/views/dashboard/index.vue
First need the back-end PR for oms-statutory [#226](https://github.com/AEGEE/oms-statutory/pull/226)
> feat: add statutory events on dashboard

- src/views/events/BoardView.vue
+ Will auto select your board if you are only a board member of one antenna
+ Will not print the select option if you are only a board member of one local
> feat: auto select board in board view

- src/fontawesome.js
- src/views/statutory/EditPositionModal.vue
- src/views/statutory/PositionsList.vue
- link position to a body
- adds option for JC to easily 'delete' a position from the list
has backend support from [this PR](https://github.com/AEGEE/oms-statutory/pull/259)
> Candidature update

- src/components/layout/FooterBar.vue
Fixed the comments on #290 
@serge1peshcoff did you do stuff with the CORS proxy already?
> chore(footer): ui changes. Fixes MEMB-432

- src/router/routes.js
- src/services.json
- src/views/auth/ConfirmToken.vue
- src/views/auth/Login.vue
- src/views/auth/PasswordConfirm.vue
- src/views/auth/PasswordReset.vue
- src/views/auth/Register.vue
- src/views/core/bodies/AddBoundCircleModal.vue
- src/views/core/bodies/AddFeePaymentModal.vue
- src/views/core/bodies/Edit.vue
- src/views/core/bodies/List.vue
- src/views/core/bodies/Single.vue
- src/views/core/bodies/ViewJoinRequests.vue
- src/views/core/bodies/ViewMembers.vue
- src/views/core/campaigns/Edit.vue
- src/views/core/campaigns/List.vue
- src/views/core/campaigns/Single.vue
- src/views/core/campaigns/ViewMembers.vue
- src/views/core/circles/AddMemberModal.vue
- src/views/core/circles/Edit.vue
- src/views/core/circles/EditMemberPositionModal.vue
- src/views/core/circles/Single.vue
- src/views/core/circles/ViewMembers.vue
- src/views/core/members/Edit.vue
- src/views/core/members/EditPrimaryBodyModal.vue
- src/views/core/members/EditUser.vue
- src/views/core/members/List.vue
- src/views/core/members/Single.vue
- src/views/core/permissions/Edit.vue
> New core refactor

- src/views/auth/Register.vue
- src/views/core/members/Edit.vue
just realized you cannot register because of the missing fields (specifically, date_of_birth, it's not required but when it's not provided it doesn't work properly, will also fix it on backend).
also enforced these fields so you cannot register without specifying all of it (except "About me").
also picking only required fields when sending it to client (need to do it for everything though).
can someone review this asap?
> fix(register): fix registering

- .eslintrc.js
- src/services.json
- src/views/dashboard/Calendar.vue
- src/views/dashboard/index.vue
- src/views/events/Accepted.vue
- src/views/events/Apply.vue
- src/views/events/BoardView.vue
- src/views/events/ChangeStatus.vue
- src/views/events/Edit.vue
- src/views/events/List.vue
- src/views/events/Participants.vue
- src/views/events/ServiceAdmin.vue
- src/views/events/Single.vue
- src/views/static/About.vue
- src/views/static/Status.vue
shortening the API prefix for events, the frontend part.
> fix(events): use shorter prefix

- src/views/core/members/Single.vue
fixed displaying the "edit" button for user himself, if he doesn't have the global permission to edit stuff
> fix(core): fixed edit permission for user

- src/services.json
- src/views/discounts/AddCodes.vue
- src/views/discounts/CategoriesList.vue
- src/views/discounts/CategoryEdit.vue
- src/views/discounts/DiscountsList.vue
- src/views/discounts/Edit.vue
- src/views/discounts/List.vue
- src/views/discounts/MyDiscounts.vue
- src/views/static/About.vue
- src/views/static/Status.vue
> fix(discounts): use shorter prefix

- src/auth.js
frontend changes for https://github.com/AEGEE/core/pull/54
> fix(logout): fixed /logout query

- src/styles/main.scss
Change the vi 1.0 colours for the current vi 2.0 ones.
> fix: update to right vi 2.0 colours

- src/views/core/members/List.vue
1) removed the infinite loading for /members
2) using backend pagination and sorting for listing
3) displaying registration date and sorting by it
> feat(members): add backend pagination and sorting for members list

- src/views/statutory/EditCandidate.vue
- src/views/statutory/ViewCandidateModal.vue
Data not shown nor fillable anymore
> fix: gender data removed from candidatures. MA-25

- src/views/core/circles/ViewMembers.vue
Related: HELP-1204
Already done on the ViewMembers page for bodies, but not for circles.
> feat(circle): add total amount of members

- src/views/core/bodies/Edit.vue
- src/views/core/bodies/Single.vue
- src/views/statutory/PositionsList.vue
Adds a new field "task description" to all bodies. This field is used to give a description of the work to be done in the statutory positions
> feat(bodies): add task description to bodies

- src/views/core/circles/ViewMembers.vue
backend now returns total entries count, so I made use of it.
> fix(members): fixed circles members count. Fixes HELP-1213

- src/views/core/bodies/CreateMember.vue
Fixes 4.1 of https://myaegee.atlassian.net/browse/HELP-1264
I've changed the redirect to a body members page, seems more obvious.
> fix(members): fix redirect when creating a member in body. Fixes HELP-1264

- src/views/core/bodies/ViewJoinRequests.vue
when approving a join request, its status isn't updated, this is fixed with this PR.
> fix(join requests): fix buttons after approving. Fixes HELP-1275

- docker/frontend-nginx/sites/default.conf
1) do not return 500 because of the recursive calls when index.htm is not found
2) changed comments a bit, removed /services prefix as it's removed in all services
> fix(nginx): fix nginx config

- src/views/core/bodies/Edit.vue
- src/views/core/bodies/Single.vue
+ fixed a few Vue warnings, when a prop is a string instead of a boolean
> feat(bodies): added bodies and website. Fixes MA-72

- src/views/core/bodies/List.vue
frontend for displaying deleted bodies
> feat(bodies): allow displaying deleted bodies

- src/fontawesome.js
- src/views/core/bodies/Single.vue
step 7 of https://myaegee.atlassian.net/browse/MA-40
> feat(bodies): allow undeleting bodies. Fixes MA-40

- src/views/statutory/PositionsList.vue
On request of JC I'm updating the infobox.
> chore(statutory): Update infobox PositionsList

- src/views/statutory/EditPositionModal.vue
- src/views/statutory/PositionsList.vue
> feat: add term dates and requirements positions

- src/views/static/ConfluencePage.vue
- src/views/static/Resources.vue
> fix(resources): Update Resources page and add mailing lists page.

- public/index.html
- src/views/events/List.vue
Now that there is a link to the helpdesk in the menu, the report a bug button is no longer necessary!
> Remove bug button

- public/index.html
- src/views/events/List.vue
- src/views/statutory/PositionsList.vue
Sorry that the branch name is weird, my Git does not want to work with me tonight 😅
> feat(positions): Add final deadline field statutory positions

- src/views/statutory/QuestionLinesList.vue
No work needs to be done on the backend for this.
> fix(question line): Add timestamp of question. Fixes HELP-1337

- src/views/statutory/ListMembersLists.vue
Fixes [MA-116](https://myaegee.atlassian.net/browse/MA-116)
> Add field "last updated" to memberslist

- src/views/statutory/EditCandidate.vue
Fixes [MA-109](https://myaegee.atlassian.net/browse/MA-109)
> feat: add tooltip language for candidates

- src/views/statutory/EditApplication.vue
Fixes [MA-123](https://myaegee.atlassian.net/jira/software/c/projects/MA/issues/MA-123), and also implements that you auto-select your primary body, and not just the first body in the list
Should be merged together with [statutory-#422](https://github.com/AEGEE/statutory/pull/422)
> fix(statutory): only allow applications from valid bodies

- src/views/statutory/UploadMembersList.vue
This should compare a number to a number again
> fix(memberslist): remove negation mark from length

- src/views/core/bodies/BulkImport.vue
Dutch last names likes van den Bosch or whatever should actually be vandenbosch instead of van.den.bosch
I think it is also better for other last names like Sanchez Hernandez imo
> fix(import): combine multiple lastnames to one word

- src/views/static/Resources.vue
To be merged and deployed on 1st of December 2020
> chore(resources): add AEGEE database. Fixes HELP-1386

- src/views/core/bodies/Edit.vue
- src/views/core/bodies/List.vue
- src/views/core/bodies/Single.vue
Frontend for https://github.com/AEGEE/core/pull/193
> feat(body): add abbreviation

- package-lock.json
- package.json
Probably it's just the @fullcalendar/vue update, but I'm reverting all three just to be sure. We need to figure out how to use the other syle-loader later
> chore(deps): revert fullcalendar

- src/views/statutory/PositionsList.vue
Fixes [MA-164](https://myaegee.atlassian.net/jira/software/c/projects/MA/issues/MA-164?filter=myopenissues)
> fix(position): display page correctly when there are no positions

- src/views/static/Resources.vue
Will be deployed after approval of AEGEE-Academy
> chore(resources): add request a trainer. Fixes HELP-1459

- src/components/tooltips/URLTooltip.vue
- src/views/summeruniversity/Edit.vue
> fix(SU): small fixes

- src/views/core/members/Edit.vue
- src/views/core/members/EditPrimaryEmailModal.vue
- src/views/core/members/Single.vue
Add the option for users to select which email address they want to use for notifications. Fixes [MA-134](https://myaegee.atlassian.net/browse/MA-134)
> fix(user): allow users to choose notification email. Fixes MA-134

- src/views/auth/Login.vue
The change was incoorporated in core already, but not in the frontend input validation
> fix(login): allow username. Partially fixes HELP-1463

- src/validate-user.js
I will create an MA issue where we can think about the possible proper fixes
> fix(user): allow users to be only of Other bodies. Fixes HELP-1554

- src/validate-user.js
- src/views/auth/Register.vue
- src/views/core/members/UpdateProfile.vue
Frontend for https://github.com/AEGEE/core/pull/233
> fix(username): force usernames to not only have numbers

- src/views/events/Edit.vue
- src/views/summeruniversity/ChangeStatus.vue
- src/views/summeruniversity/Edit.vue
- src/views/summeruniversity/EditSecond.vue
- src/views/summeruniversity/Single.vue
To be merged with https://github.com/AEGEE/summeruniversity/pull/25
> fix(su): change status underscores to spaces

- src/views/static/Resources.vue
To be merged after clarification of JC on which version is to be used until the ratification by the Agora
> chore(resources): update Strategic Plan

- src/views/core/bodies/Edit.vue
- src/views/core/bodies/Single.vue
Implements [MA-181](https://myaegee.atlassian.net/browse/MA-181?atlOrigin=eyJpIjoiZjY4ZTliMTMyYWIxNGQ5MDk1OTFlZmEyMzFlYmEzNjkiLCJwIjoiaiJ9)
Needs to be merged together with [core#259](https://github.com/AEGEE/core/pull/259)
> feat(body): add postal address bodies

- src/views/dashboard/Calendar.vue
- src/views/summeruniversity/ChangeStatus.vue
- src/views/summeruniversity/Edit.vue
- src/views/summeruniversity/EditSecond.vue
- src/views/summeruniversity/Single.vue
Frontend for https://github.com/AEGEE/summeruniversity/pull/48
> feat(su): add validation TODOs and event publication

- src/views/core/bodies/AddMemberModal.vue
- src/views/core/bodies/CreateMember.vue
- src/views/core/bodies/ViewMembers.vue
Needs to be deployed with https://github.com/AEGEE/core/pull/249
> fix(member): add member to body

- src/views/summeruniversity/Single.vue
After this, every public field (except for 'photos' and 'video') can be viewed on the frontend.
Photos and video preview will be added at a later point
> fix(su): display full summeruniversity

- src/views/static/Resources.vue
site.aegee.org is temporarily offline, so this is the best time to comply more to the DPPS
> chore(resources): move SP and AA to KMS Drive

- src/views/statutory/VotesAmounts.vue
@WikiRik does the CSV need a header line?
> feat(MA-24): csv export of body votes for statutory events 

- src/views/core/bodies/AddMemberModal.vue
It was not clear what fields people could search for. Now that should be fixed
> fix(add member): add placeholder to field

- src/views/core/bodies/Edit.vue
- src/views/core/bodies/Single.vue
And also hide the optional fields from the body page if they are not filled.
> fix(bodies): visibly mark required

- src/views/statutory/Juridical.vue
Frontend for https://github.com/AEGEE/statutory/pull/540
> feat(agora): add export delegates OMS JC

- src/views/static/Resources.vue
For the ones that have not seen HELP-1818; it's a request by the new Network Director so the changes are CD approved
> fix(resources): update resources. Fixes HELP-1818

- .circleci/config.yml
Needed for semantic release, other updates like done in https://github.com/AEGEE/discounts/pull/333 will be added later
> chore(circleci): update dbap docker image

- src/views/core/members/Single.vue
Frontend for https://github.com/AEGEE/core/pull/400
> fix(superadmin): add superadmin buttons

- src/views/summeruniversity/Edit.vue
- src/views/summeruniversity/EditSecond.vue
- src/views/summeruniversity/List.vue
Addition of the most basic season implementation. Better implementation will follow later, but this should be good for the coming SUs
> fix(su): add seasons

- src/menu.json
> add ideas platform to menu.json

- src/views/statutory/Export.vue
> fix(statutory): only filter on participant type when allowed to export all

- src/views/statutory/ViewApplication.vue
This is a bandaid, some fields will be returned empty. See https://github.com/AEGEE/statutory/pull/968
> fix(statutory): only show answers when given

- src/views/statutory/MassMailer.vue
See https://github.com/AEGEE/statutory/pull/977
> fix(statutory): add statutory id to massmailer

- src/views/statutory/Incoming.vue
- src/views/statutory/MassMailer.vue
- src/views/statutory/Stats.vue
While the incoming form is not yet fillable in MyAEGEE, this at least allows LO to mark manually which ones filled it in and email the others
> feat(statutory): allow LO to check if incoming form is filled

- src/views/statutory/QuestionLinesList.vue
> fix(statutory): update question line information

- src/auth.js
> style: remove unnecessary return statement

- src/views/events/Edit.vue
- src/views/events/Single.vue
Fully based on [Frontend#1784](https://github.com/AEGEE/frontend/pull/1784), fixes part of [MA-206](https://myaegee.atlassian.net/browse/MA-206)
Needs [Events#967](https://github.com/AEGEE/events/pull/967)
[MA-206]: https://myaegee.atlassian.net/browse/MA-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(events): add option to create fully vegetarian events
